# Generated by Django 3.2.5 on 2022-03-19 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('usn', models.CharField(blank=True, max_length=20, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('sem', models.IntegerField(blank=True, default=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('credits', models.IntegerField(blank=True, default=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditsEarned', models.IntegerField(blank=True, default=4, null=True)),
                ('cie', models.IntegerField(blank=True, null=True)),
                ('see', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
                ('sname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nmit.student')),
                ('subname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nmit.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='gpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgpa', models.IntegerField(blank=True, default=0, null=True)),
                ('cgpa', models.IntegerField(blank=True, default=0, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('sem', models.IntegerField(blank=True, default=5, null=True)),
                ('sname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nmit.student')),
            ],
        ),
    ]
