# Generated by Django 3.2.5 on 2022-05-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmit', '0004_auto_20220505_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpa',
            name='creditsEarn',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gpa',
            name='creditsReg',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
