# Generated by Django 3.2.5 on 2022-05-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmit', '0005_auto_20220505_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='cie',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='creditsEarned',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='see',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='total',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
