# Generated by Django 3.2.5 on 2022-05-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmit', '0006_auto_20220505_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='credits',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
    ]
