# Generated by Django 3.2.5 on 2022-11-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmit', '0008_alter_gpa_sgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpa',
            name='cgpa',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
    ]
